let products = [
    {id:1, name:"Blouse", price:35000, img: 'images/blouse.png', description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:2, name:"Pants", price:85000, img: 'images/pants.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:3, name:"Dress", price:55000, img: 'images/dress.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:4, name:"Crop-top", price:25000, img: 'images/crop-top.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:5, name:"Skirt", price:50000, img: 'images/skirt.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:6, name:"T-Shirt", price:40000, img: 'images/t-shirt.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:7, name:"Shorts", price:65000, img: 'images/shorts.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:8, name:"Coat", price:95000, img: 'images/coat.png', description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:9, name:"Jacket", price:120000, img: 'images/jacket.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},
    {id:10, name:"Scarf", price:20000, img: 'images/scarf.png',  description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda quas, ducimus numquam, ea possimus quae tenetur nesciunt explicabo quidem nobis, dolores iure odit iste. Molestias mollitia aperiam modi praesentium at."},  
  ];